# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

paircomps <- function(pair_geno, LOD, geno1, geno2, symmo, granulum, granulum_loci) {
    .Call(kinference_paircomps, pair_geno, LOD, geno1, geno2, symmo, granulum, granulum_loci)
}

HSP_paircomps_lots <- function(pair_geno, LOD, geno1, geno2, symmo, eta, min_keep_PLOD, bins) {
    .Call(kinference_HSP_paircomps_lots, pair_geno, LOD, geno1, geno2, symmo, eta, min_keep_PLOD, bins)
}

POP_paircomps_lots <- function(geno1, geno2, symmo, eta, max_keep_Nexclu, bins, AAO, BBO) {
    .Call(kinference_POP_paircomps_lots, geno1, geno2, symmo, eta, max_keep_Nexclu, bins, AAO, BBO)
}

POP_wt_paircomps_lots <- function(geno1, geno2, w, symmo, eta, max_keep_wpsex, bins, AAO, BBO) {
    .Call(kinference_POP_wt_paircomps_lots, geno1, geno2, w, symmo, eta, max_keep_wpsex, bins, AAO, BBO)
}

DUP_paircomps_lots <- function(geno1, geno2, symmo, max_diff_genos) {
    .Call(kinference_DUP_paircomps_lots, geno1, geno2, symmo, max_diff_genos)
}

indiv_lglk_geno <- function(lpgeno, geno) {
    .Call(kinference_indiv_lglk_geno, lpgeno, geno)
}

K_indiv <- function(tt, geno, vec_LOD, Pg) {
    .Call(kinference_K_indiv, tt, geno, vec_LOD, Pg)
}

